apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-term-configmap
  namespace: payment-term
data:
  BOOTSTRAP_SERVERS: neutral-primate-14295-eu1-kafka.upstash.io:9092
  SASL_MECHANISM: SCRAM-SHA-256
  SECURITY_PROTOCOL: SASL_SSL