apiVersion: v1
kind: Secret
metadata:
  name: payment-term-secret
  namespace: payment-term
type: Opaque
data:
  kafka_username: replace_with_upstash_kafka_username
  kafka_password: replace_with_upstash_kafka_password